/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import java.io.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
         try {
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting("Jon", "Roquelaure"));
         } catch(IOException e) {
            // nothing
        }
    }
}
